### ISSUE TITLE
[코테 스터디 준비 사이트 : SUP]

### ISSUE THREAD

**Issue by moong23** [chaesc1/ssafyAlgorithmStudy12#55]
안녕하세요
따로 메일 드릴 수 있는 연락처를 찾지 못해 Issue 드립니다!
싸피 11기 서울반에서 짧은 시간 보내다 퇴소한 김문기라고 합니다 :)
싸피 활동을 할 때 여러 스터디들이 모두 풀지 않았던 공통된 문제를 찾느라 고생하는것을 보고
코테 스터디를 위한 문제 추천 사이트를 제작해 운영하고 있습니다.

[사이트 기능]
리드미에 달아놓으신 tony님의 백준 문제집에서 n명의 스터디원이 모두 풀지 않은 문제를
추천 받을 수 있습니다.

[사이트 주소]
https://sup-algorithm.netlify.app/

편하게 사용하시고, 피드백 주신다면 더 좋은 사이트를 만드는데 도움이 될 것 같습니다 :)

감사합니다~!

**Comment by chaesc1** [comment]
이거 링크 사용하면 되는건가요??

**Comment by moong23** [comment]
네 링크 사용하시면 됩니다!

**Comment by chaesc1** [comment]
감사합니다!!

**Comment by moong23** [comment]
싸피 안에서도 널리 홍보해주시면 감사드리겠습니다 :)

**Comment by chaesc1** [comment]
싸피 매터모스트 채널에 올려두 될까요!!?

**Comment by moong23** [comment]
네 올려주시면 감사드리겠습니다 :)
